### ISSUE TITLE
 Creating componentENOENT: no such file or directory rg.config.json

### ISSUE THREAD

**Issue by dnlmelo** [arminbro/generate-react-cli#100]
**Describe the bug**
No such file or directory, rg.config.json in npx cache, after run npx react-generate-cli component X

**To Reproduce**
 npx react-generate-cli component X

**Expected behavior**
Create the component

**Machine (please complete the following information):**
- OS Windows
 - Node Version 20.x

**Comment by arminbro** [comment]
@dnlmelo I'm not sure what you're referring to. The command you provided is Invalid.

Valid command ✅ :
```shell
npx generate-react-cli component X
``` 

Invalid command ❌ :
```shell
npx react-generate-cli component X
```

I hope this help. I'm going to close this issue for now.
