### ISSUE TITLE
Additional Config Options

### ISSUE THREAD

**Issue by meandillar** [arminbro/generate-react-cli#21]
**Describe the solution you'd like**

1. An option to specify CSS naming convention

For example if I generated a new component called _MyButton_ and specified kebab case for the css it would change this:

```
const TemplateName = () => <div className="TemplateName">TemplateName Component</div>
```

to this:

```
const MyButton = () => <div className="my-button">MyButton Component</div>
```

and CSS file would be:

```
.my-button {}
```

2. Be able to specify an array for multiple files in the `"customTemplates"` option

Most of the time I use a _MyComponent.stories.css_ file for extra Storybook styling. Would be great to be able to generate multiple CSS files using an array like this:

```
{
  ...,
  "component": {
    "default": {
      "customTemplates": {
        "component": "src/components/__template__/Template.js",
        "story": "src/components/__template__/Template.stories.js",
        "style": ["src/components/__template__/Template.css", "src/components/__template__/Template.stories.css"],
        "test": "src/components/__template__/Template.test.js"
      },
  ...
}
```

**Comment by boostup** [comment]
:+1: 

With regards to @meandillar point 1 about CSS naming convention :
- IMHO : the package [`decamelize`](https://www.npmjs.com/package/decamelize) could do the job, but it should be optional to have a `decamilzed` CSS `className`, where the `TemplateName` would still be the default naming option for the CSS `className`.

thanx ! this package is filling a real need !  

**Rhetorical question** : Why isn't the Create-React-App CLI providing this functionnality ... This is about the only thing I miss about the angular ecosystem, of which the CLI provided this by de facto !
