### ISSUE TITLE
Could not determine executable to run

### ISSUE THREAD

**Issue by JacopoDioBrando** [arminbro/generate-react-cli#29]
**Describe the bug**
npm raises an issue and produces a log instead of creating generate-react-cli .json and folder's name component

**To Reproduce**
1. Create project via Create React App using command `npx create-react-app projectName --template redux-typescript`
2. Install generate-react-cli via command `npm i generate-react-cli`
3. Try to create a component via grc (e.g. `npx generate-react-cli component Login`)

**Expected behavior**
Creation of grc .json template and component name folder

**Machine (please complete the following information):**
 - macOS Mojave 10.14.6
 - Node Version 15.0.1
 - NPM 7.0.3
 - VS Code 1.50.1
 - Create React App 4.0.0
 - generate-react-cli 5.1.0

**Log Example**
`0 verbose cli [
0 verbose cli   '/Users/diobrando/.nvm/versions/node/v15.0.1/bin/node',
0 verbose cli   '/Users/diobrando/.nvm/versions/node/v15.0.1/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'generate-react-cli',
0 verbose cli   'c',
0 verbose cli   'Login'
0 verbose cli ]
1 info using npm@7.0.3
2 info using node@v15.0.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/Users/diobrando/.nvm/versions/node/v15.0.1/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/diobrando/Src/cra-ts-redux-login/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/diobrando/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/Users/diobrando/.nvm/versions/node/v15.0.1/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session ba5fa4d42bd9b664
20 timing npm:load Completed in 21ms
21 http fetch GET 200 https://registry.npmjs.org/generate-react-cli 23ms (from cache)
22 timing command:exec Completed in 53ms
23 verbose stack Error: could not determine executable to run
23 verbose stack     at getBinFromManifest (/Users/diobrando/.nvm/versions/node/v15.0.1/lib/node_modules/npm/lib/exec.js:247:23)
23 verbose stack     at exec (/Users/diobrando/.nvm/versions/node/v15.0.1/lib/node_modules/npm/lib/exec.js:130:15)
24 verbose cwd /Users/diobrando/Src/cra-ts-redux-login
25 verbose Darwin 18.7.0
26 verbose argv "/Users/diobrando/.nvm/versions/node/v15.0.1/bin/node" "/Users/diobrando/.nvm/versions/node/v15.0.1/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "generate-react-cli" "c" "Login"
27 verbose node v15.0.1
28 verbose npm  v7.0.3
29 error could not determine executable to run
30 verbose exit 1
<img width="581" alt="Screenshot 2020-11-03 at 02 49 57" src="https://user-images.githubusercontent.com/16334866/97937541-4aec8a00-1d7f-11eb-8ea1-d81ee612bbca.png">
`

Create React App package.json
`{
  "name": "cra-ts-redux-login",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@reduxjs/toolkit": "^1.4.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/jest": "^24.9.1",
    "@types/node": "^12.19.3",
    "@types/react": "^16.9.55",
    "@types/react-dom": "^16.9.9",
    "@types/react-redux": "^7.1.10",
    "generate-react-cli": "^5.1.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-scripts": "4.0.0",
    "typescript": "~3.8.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Screenshots**

**Comment by arminbro** [comment]
I followed your steps to reproduce the error you see, but it worked just fine on my machine. I notice you're using `Node Version 15.0.1`. I recommend using the LTS version instead (the latest LTS version at the moment is `14.15.5`). Try it out and let me know if you're still having the issue. 

I'm going to close this ticket for now.
