### ISSUE TITLE
styled components

### ISSUE THREAD

**Issue by craigryan** [arminbro/generate-react-cli#48]
Nice tool, thanks!

would be great to include 'styled' for cssPreprocessor (see https://styled-components.com/) which generates a simple style.ts for the component imports, perhaps with a default Container just to get started:

```
// style.ts
import styled from 'styled-components';
const Container = styled.div`
  padding: 5px;
`
const Styles = {
  Container,
};

export default Styles;
```
`

**Comment by luxplanjay** [comment]
This is a common use case, might get on it when I get some free time. Naming should be ComponentName.styled.{js,ts} as a default, but also configurable.
