### ISSUE TITLE
Whenever i try to create a component in a subfolder the subfolder declarations appear on the component declaration.

### ISSUE THREAD

**Issue by tomkidumbuyo** [arminbro/generate-react-cli#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Machine (please complete the following information):**
 - OS: [e.g. macOS Mojave]
 - Node Version [e.g. v10.16.1]

**Additional context**

**Screenshots**

**Comment by arminbro** [comment]
HI @tomkidumbuyo,

I believe you're looking for the `--flat` flag. You'll find it in the [options](https://github.com/arminbro/generate-react-cli#options) table.

Example:
```shell
npx generate-react-cli component Box --flat
```
That command will generate the component files without a directory.

I will close this ticket now, as I believe this flag resolves your request.
