### ISSUE TITLE
Only Pascal casing seems to work for custom templates

### ISSUE THREAD

**Issue by LokeSonne** [arminbro/generate-react-cli#54]
**Describe the bug**
When I try to use anything other than Pascal-case for the files in my custom templates, they are not replaced.

**To Reproduce**
1. Create a custom template for component 
2. name it template-name.tsx
3. Add the custom template in generate-react-cli.json 
`  "component": {
    "default": {
      "customTemplates": {
        "component": "./templates/template-name.tsx"
      },`
4. Run the cli, e.g.  npx generate-react-cli component MyComponent  
5. The component file in the created component has not been changed from template.name.tsx
**Expected behavior**
The filename should be my-component.tsx but is template-name.tsx

**Machine (please complete the following information):**
 - OS: [e.g. macOS Mojave]
 - Node Version [e.g. v10.16.1]

**Additional context**

**Screenshots**

**Comment by edustefsb** [comment]
This and also the folder name should respect the same case sensitivity as the command for example:

`npx generate-react-cli component demo` should generate a folder called `demo` not `Demo`

**Comment by ahmet-cetinkaya** [comment]
> This and also the folder name should respect the same case sensitivity as the command for example:
> 
> `npx generate-react-cli component demo` should generate a folder called `demo` not `Demo`

Nope, it still doesn't work that way.

**Comment by arminbro** [comment]
We now support any component filename format. Please check the PR above ☝️for more details.
