### ISSUE TITLE
Page creation using existing directory

### ISSUE THREAD

**Issue by 17110608** [arminbro/generate-react-cli#64]
Please give the option to create the page in the existing folder path, rather than creating the new folder for it.
Configuration: `   "page": {
      "customTemplates": {
        "component": "src/app/templates/page/TemplateName.js"
      },
      "path": "src/app/pages/user",
      "withStyle": false,
      "withTest": false,
      "withStory": false,
      "withLazy": false
    }`

When we run `npx generate-react-cli component Test --type=page` it creates the page in `src/pages/Test/Test.js`
I wanted that should not create a new directory for it, because it is a page. It should use existing directory to add the new page which we are created.

**Comment by themse** [comment]
I also come across with this issue working with NextJS. Pls help
