### ISSUE TITLE
Custom templated filenames cannot be formatted to different cases

### ISSUE THREAD

**Issue by nick3point5** [arminbro/generate-react-cli#65]
Custom templated filenames cannot be formatted to different cases.

If "*template-name.jsx" is used as a template file, GRC will ignore it and produce that filename without replacing it with the component name in kebab-case.

**Comment by nick3point5** [comment]
feature added in https://github.com/arminbro/generate-react-cli/pull/66

**Comment by arminbro** [comment]
We now support any component filename format. Please check the PR above ☝️for more details.
