### ISSUE TITLE
Shorten commands with aliases

### ISSUE THREAD

**Issue by maksim-zakharov** [arminbro/generate-react-cli#70]
Hi

1. I would like to shorten the length of the command, for example like this:

`npx grc c Box --test=false`

2. I also want to be able to write the component type without the flag, for example like this:

```
npx grc page BoxPage
npx grc p BoxPage
```

where page/p is the alias to the component -type=page command

3. I want custom operators, for example I want to add "withStore" which will add a file with storeApi for redux toolkit query

 4. I also want to be able to configure aliases for component types, for example:

```
// config.json

{
...
 "aliases": {
    "page": "p"
    ...
  }
}
```

**Comment by arminbro** [comment]
Hi @maksim-zakharov,

You should be able to create aliases directly inside your `package.json` file via scripts.

Example:
```json
// package.json

"scripts": {
  "gc": "npx generate-react-cli c",
  "gp": "npx generate-react-cli c --type=page."
},
```
So in my example above, I have an alias of `gc`, short for generate-component, and I can run the command like so:
```shell
npm run gc Box
```

and `gp`, short for generate-page:
```shell
npm run gp SomePage
```

You might need to add double hyphens `--` if you want to chain additional flags.  You can read more here: https://docs.npmjs.com/cli/v8/commands/npm-run-script

I hope this was helpful and resolves your request. I'm going to close this issue for now.
