### ISSUE TITLE
Pascal case component generation broken

### ISSUE THREAD

**Issue by TravisYeah** [arminbro/generate-react-cli#75]
**Describe the bug**
Pascal case components produce broken naming conventions. Example:

```ts
import React, { FC } from 'react';
import styles from './TempTest.module.css';

interface TEMP TESTProps {}

const TEMP TEST: FC<TEMP TESTProps> = () => (
  <div className={styles.TEMP TEST} data-testid="TEMP TEST">
    TEMP TEST Component
  </div>
);

export default TEMP TEST;

```

**To Reproduce**
In a new npm project run `npx generate-react-cli component TempTest` and accept all default cli options.

**Expected behavior**
Naming should be `TempTest`.

**Machine (please complete the following information):**
Node 18.12.0

**Comment by arminbro** [comment]
Thanks for reporting, @TravisYeah. You should now be able to generate your components with the pascal case.
