### ISSUE TITLE
Add context, custom hook and redux toolkits modules templates

### ISSUE THREAD

**Issue by ehsan-shv** [arminbro/generate-react-cli#92]
`generate-react-cli` is a fantastic tool for React developers, especially when working on large-scale applications. However, I believe that it could be improved by adding the ability to automatically generate **custom hook modules**, **context modules**, and **Redux toolkit modules**, along with their respective testing files.

**Comment by arminbro** [comment]
Hi @ehsan-shv,

Can you show an example of what you're describing?

With the combination of [Custom component templates](https://github.com/arminbro/generate-react-cli#custom-component-templates) and [Custom component files](https://github.com/arminbro/generate-react-cli#custom-component-files) should provide you with the flexibility of generating any costume react files as you need.

**Comment by arminbro** [comment]
I trust that my earlier advice was beneficial in addressing your query. Since there hasn't been any recent activity, I'll be closing this issue. Feel free to reach out if you need any further assistance!
