### ISSUE TITLE
Built-in scripts to improve user experience

### ISSUE THREAD

**Issue by ehsan-shv** [arminbro/generate-react-cli#93]
Adding new components by `npx generate-react-cli component Box` command is easy enough, but there is definitely room for improvement to make the experience even more user-friendly. Maybe adding scripts to `package.json` is a good way to make it better. I just wrote this script to handle it better in my projects: 
```js
// create.js
const readline = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout,
})

readline.question('Enter component name(PaskalCase):', (name) => {
  readline.question('Enter component type(component, page, layout):', (type) => {
    const { exec } = require('child_process')
    if (type === 'component') {
      exec(`npx generate-react-cli component ${name}`, (error, stdout, stderr) => {
        if (error) {
          console.log(`Error: ${error.message}`)
          return
        }
        if (stderr) {
          console.log(`stderr: ${stderr}`)
          return
        }
        console.log(`stdout: ${stdout}`)
      })
    } else if (type === 'layout' || type === 'page') {
      exec(`npx generate-react-cli component ${name} --type=${type}`, (error, stdout, stderr) => {
        if (error) {
          console.log(`Error: ${error.message}`)
          return
        }
        if (stderr) {
          console.log(`stderr: ${stderr}`)
          return
        }
        console.log(`stdout: ${stdout}`)
      })
    } else {
      console.log(`Invalid component type: ${type}`)
    }
    readline.close()
  })
})
```
```
// package.json
  "scripts": {
    "create": "node ./create.js"
  },
```
So I and no other developer in the project have not to remember `npx generate-react-cli component Box`  script to create a new component and we can easily run `yarn run create`.
But I know that it's not enough, so you can definitely make it better by refactoring and adding a built-in script for `react-generate-cli`.

**Comment by arminbro** [comment]
Hi @ehsan-shv 

You should be able to create aliases directly inside your `package.json` file via scripts.

Example:
```json
// package.json

"scripts": {
  "gc": "npx generate-react-cli c",
  "gp": "npx generate-react-cli c --type=page"
},
```
So in my example above, I have an alias of `gc`, short for generate-component, and I can run the command like so:
```shell
npm run gc Box
```

and `gp`, short for generate-page:
```shell
npm run gp SomePage
```

You can also use the double hyphens `--` if you want to chain additional flags.  You can read more here: https://docs.npmjs.com/cli/v9/commands/npm-run-script?v=true

I hope this was helpful and resolves your request. I'm going to close this issue for now.
