### ISSUE TITLE
allow to customize folder naming convention

### ISSUE THREAD

**Issue by bureyburey** [arminbro/generate-react-cli#96]
First of all, this is a great and useful tool :)

How about adding the ability to customize the folder naming convention (snake_case/kebab-case/camelCase/PascalCase/....)

at the moment you can only control both the folder name AND the file name.

but if I were to need a `kebab-case-folder-name/KebabCaseComponentName.tsx` structure it cannot be controlled at the moment.

**Comment by TyIsI** [comment]
I'm also interested in this for the purpose of templating component names.

Example:
`generate-react component --type=provider Example` creates a `src/providers/ExampleProvider` directory that would look like this:
```
src/providers/ExampleProvider
src/providers/ExampleProvider/Example.context.ts
src/providers/ExampleProvider/ExampleProvider.types.ts
src/providers/ExampleProvider/ExampleProvider.tsx
src/providers/ExampleProvider/ExampleProvider.test.tsx
src/providers/ExampleProvider/ExampleProvider.stories.tsx
```

`Example.context.ts` could look like this:
```
import { createContext } from 'react'

import { type ExampleContextType } from './ExampleProvider.types'

export const defaultExampleContext: ExampleContextType = {}

export const ExampleContext = createContext(defaultExampleContext)
```

Disclaimer: Yes, it could be argued that the containing directory could simply be called `Example`, but for the sake of flexibility I think it would be good to be able to use a template name for the target directory.

**Comment by TyIsI** [comment]
@bureyburey I opened #98 for this
